server:
  context-path: /${spring.application.name}
  port: 8443
  ssl:
    client-auth: WANT

management:
  context-path: /mgmt
  security:
    roles: Administrator,JBossAdministrator

endpoints:
  health:
    sensitive: false

security:
  sessions: STATELESS
  basic.enabled: false
  enable-csrf: false
  user.password: passwordNotUsed
  jwt.ttl: 86400
  issuers-required: true

spring:
  rabbitmq:
    host: ${MESSAGING_SERVER_HOSTNAME:localhost}
  cloud:
    consul:
      enabled: false

hazelcast:
  client:
    clusterName: cache

swagger:
  doc:
    packages: datawave.microservice
