warehouse-cluster:
  accumulo:
    zookeepers: ${accumulo.zookeepers}
    instanceName: ${accumulo.instanceName}
    username: ${accumulo.username}
    password: ${accumulo.password}

# Example lookup and lookup-audit config, if desired

#accumulo:
#  lookup:
#    numQueryThreads: 5
#    audit:
#      defaultAuditType: 'ACTIVE'
#      tableConfig:
#        - tableRegex: 'datawave\.shard'
#          rowRegex: '2011.*'
#          colFamRegex: '.*'
#          colQualRegex: '.*'
#          auditType: 'NONE'
#
#        - tableRegex: 'datawave\.shard'
#          rowRegex: '2013.*'
#          colFamRegex: '.*'
#          colQualRegex: '.*'
#          auditType: 'PASSIVE'

# Enable auditing (for lookup queries only), if desired

audit-client:
  enabled: false
  uri: '${AUDIT_SERVER_URL:https://localhost:8743/audit}'

logging:
  level:
    datawave.microservice.accumulo: DEBUG
